### PR TITLE
Add screenshot to readme

### PR DESCRIPTION
**Pull request by surjithctly**
Adding a screenshot will help users understand the benefit instantly before even visiting the live demo.

### CODE REVIEW

**Comment by agneym** [comment]
Hey! This is a good idea, Thanks for contributing 😄

Can we get rid of the empty space around the component in the screenshot? It is especially disconcerting in dark mode.

**Comment by surjithctly** [comment]
Done :)

**Comment by agneym** [comment]
LGTM! Thanks for contributing 🍾

**Comment by surjithctly** [comment]
🥳

**Pull request merged**
